info:
  contact: {}
paths:
  /example/ping:
    get:
      consumes:
      - application/json
      description: 無条件に"ping OK!"と返します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping疎通確認
      tags:
      - example
  /family/animals:
    get:
      consumes:
      - application/json
      description: すべての動物を取得します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 動物全件取得
      tags:
      - family
  /family/relations:
    get:
      consumes:
      - application/json
      description: すべての親子関係を取得します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 親子関係全件取得
      tags:
      - family
swagger: "2.0"
